export const VENUE_SCREEN_LOADING = 'VENUE_SCREEN_LOADING';
export const VENUE_SCREEN_LOADED = 'VENUE_SCREEN_LOADED';
export const VENUE_SCREEN_FAILED = 'VENUE_SCREEN_FAILED';
export const SAVE_ALL_DATA = 'SAVE_ALL_DATA';

