export const VENUE_SCREEN_LOADING = 'VENUE_SCREEN_LOADING';
export const VENUE_SCREEN_LOADED = 'VENUE_SCREEN_LOADED';
export const VENUE_SCREEN_FAILED = 'VENUE_SCREEN_FAILED';
export const LOADING_ADDRESSES = 'LOADING_ADDRESSES';
export const LOADED_ADDRESSES = 'LOADED_ADDRESSES';
export const ADDRESS_API_FAIL = 'ADDRESS_API_FAIL';
export const SAVE_VENUE_DATA = 'SAVE_VENUE_DATA';
